(defun part-one ()
  (let ((input (open "input" :if-does-not-exist nil))
        (total 0))
    (loop for line = (read-line input nil)
          while line do (setf total (+ total (parse-integer line))))
    (close input)
    total))

(defun part-two ()
  (let ((input (open "input" :if-does-not-exist nil))
        (frequency-changes (make-array 5 :fill-pointer 0 :adjustable t))
        (frequency 0)
        (visited-frequencies (make-hash-table)))
    (loop for line = (read-line input nil)
          while line do (vector-push-extend (parse-integer line) frequency-changes))
    (loop (loop for change across frequency-changes
                if (gethash frequency visited-frequencies) do
                  (return-from part-two frequency)
                else do (setf (gethash frequency visited-frequencies) t)
                do (incf frequency change)))))
